// Generated by the PacketGenerator compiler.  DO NOT EDIT!
#pragma once

#include <string>

namespace network_message
{
    class fire_bullet
    {
    public:
        vector3 position_;
        vector4 rotation_;
    };
}
