// Generated by the PacketGenerator compiler.  DO NOT EDIT!
#pragma once
#include <string>

namespace network_message
{
	class move_object
	{
	public:
        vector3 position_;
        vector4 rotation_;
	};
}
